# This file has been generated by ./pkgs/misc/vim-plugins/update.py. Do not edit!
{ lib, buildVimPluginFrom2Nix, fetchFromGitHub, overrides ? (self: super: {}) }:
let
  packages = ( self:
{
  context-vim = buildVimPluginFrom2Nix {
    pname = "context-vim";
    version = "2020-10-20";
    src = fetchFromGitHub {
      owner = "wellle";
      repo = "context.vim";
      rev = "e38496f1eb5bb52b1022e5c1f694e9be61c3714c";
      sha256 = "1iy614py9qz4rwk9p4pr1ci0m1lvxil0xiv3ymqzhqrw5l55n346";
    };
    meta.homepage = "https://github.com/wellle/context.vim/";
  };

  ctrlp-modified-vim = buildVimPluginFrom2Nix {
    pname = "ctrlp-modified-vim";
    version = "2019-02-03";
    src = fetchFromGitHub {
      owner = "jasoncodes";
      repo = "ctrlp-modified.vim";
      rev = "1d51d0422b20bc61434959f5d76e60c5141ca3f8";
      sha256 = "11453ahb5x5m7nix6gwayvcvwzsggblji6rlyp5qk7avbrmd8m24";
    };
    meta.homepage = "https://github.com/jasoncodes/ctrlp-modified.vim/";
  };

  dracula-vim = buildVimPluginFrom2Nix {
    pname = "dracula-vim";
    version = "2021-10-23";
    src = fetchFromGitHub {
      owner = "dracula";
      repo = "vim";
      rev = "e5f09746562ef0226d3484a01609ceca41700a3d";
      sha256 = "1k5bwif20srhzwj8fwigrih1npjnjcvivl7sr7idspp7rig7lldk";
    };
    meta.homepage = "https://github.com/dracula/vim/";
  };

  firenvim = buildVimPluginFrom2Nix {
    pname = "firenvim";
    version = "2021-10-30";
    src = fetchFromGitHub {
      owner = "glacambre";
      repo = "firenvim";
      rev = "553c913db02952f305e71e76aa0a8f6c71eb83ff";
      sha256 = "0cv95ph3flm01r8nwckvbf77nr6mw1fg6p1rxmg024gkqhmxbp26";
    };
    meta.homepage = "https://github.com/glacambre/firenvim/";
  };

  godoctor-vim = buildVimPluginFrom2Nix {
    pname = "godoctor-vim";
    version = "2018-03-29";
    src = fetchFromGitHub {
      owner = "godoctor";
      repo = "godoctor.vim";
      rev = "17973331d1ea88bad082fba406c1690f17943b52";
      sha256 = "0si65xlgfq5rdshk0y2v7wq72zyxp7c9ckr0xljx65raa9l5dgil";
    };
    meta.homepage = "https://github.com/godoctor/godoctor.vim/";
  };

  ReplaceWithRegister = buildVimPluginFrom2Nix {
    pname = "ReplaceWithRegister";
    version = "2014-10-31";
    src = fetchFromGitHub {
      owner = "vim-scripts";
      repo = "ReplaceWithRegister";
      rev = "832efc23111d19591d495dc72286de2fb0b09345";
      sha256 = "0mb0sx85j1k59b1zz95r4vkq4kxlb4krhncq70mq7fxrs5bnhq8g";
    };
    meta.homepage = "https://github.com/vim-scripts/ReplaceWithRegister/";
  };

  splitjoin-vim = buildVimPluginFrom2Nix {
    pname = "splitjoin-vim";
    version = "2021-10-03";
    src = fetchFromGitHub {
      owner = "AndrewRadev";
      repo = "splitjoin.vim";
      rev = "48af03733f4e7a7d0449fdbb15aa70539faef7ad";
      sha256 = "0z5vcjfnrs18plcqy311qwrl1l4h9xi4r3fbijc8ald38hw6p7dk";
      fetchSubmodules = true;
    };
    meta.homepage = "https://github.com/AndrewRadev/splitjoin.vim/";
  };

  vim-case-change = buildVimPluginFrom2Nix {
    pname = "vim-case-change";
    version = "2018-05-14";
    src = fetchFromGitHub {
      owner = "icatalina";
      repo = "vim-case-change";
      rev = "e9b30040b6c81f8361154e121fd5936a4d26f5a8";
      sha256 = "191509759yzx6jwzrs7vrxr2ivb8vxpifbxyaidqnskdqkjizhgy";
    };
    meta.homepage = "https://github.com/icatalina/vim-case-change/";
  };

  vim-textobj-rubyblock = buildVimPluginFrom2Nix {
    pname = "vim-textobj-rubyblock";
    version = "2016-09-13";
    src = fetchFromGitHub {
      owner = "nelstrom";
      repo = "vim-textobj-rubyblock";
      rev = "2b882e2cc2599078f75e6e88cd268192bf7b27bf";
      sha256 = "197m0a45ywdpq2iqng6mi5qjal2qggjjww1k95iz2s7wvh8ng9yr";
    };
    meta.homepage = "https://github.com/nelstrom/vim-textobj-rubyblock/";
  };

});
in lib.fix' (lib.extends overrides packages)
