#!/bin/bash
# Thieved from https://github.com/burke/dotfiles/blob/master/.config/nvim/update
set -euo pipefail

dir="$(dirname "${BASH_SOURCE[0]}")"

mkdir -p "${dir}/bundle"

children=()

while read -r line; do
  if [[ "${line}" == "#"* || "${line}" == "" ]]; then
    continue
  fi
  line="${line%% *}"

  (
    repo="$(basename "${line}")"
    if [[ -d "${dir}/bundle/${repo}" ]]; then
      echo "%% Pulling ${repo}"
      git -C "${dir}/bundle/${repo}" pull
    else
      echo "%% Cloning ${repo}"
      git -C "${dir}/bundle" clone "https://github.com/${line}.git"
    fi
  ) &
  children+=($!)
done < "${dir}/plugin_list"

# shellcheck disable=SC2086
wait ${children[*]}
