#!/usr/bin/env ruby --disable-gems

require 'fileutils'
require 'open3'

DIR = File.expand_path(File.dirname(__FILE__))
BUNDLE_DIR = File.join(DIR, 'bundle')
PLUGIN_FILE = File.join(DIR, 'plugin_list')

FileUtils.mkdir_p(BUNDLE_DIR)

def run!(*command, **kwargs)
  o, e, s = Open3.capture3(*command, **kwargs)
  raise "Command failed: `#{command}` with output:\n#{o}\nand error:\n#{e}" unless s.success?
end

File.readlines(PLUGIN_FILE).filter_map do |line|
  line = line.split('##').first.strip
  next if line.start_with?('#') || line.empty?

  org_repo, command = line.split(' ', 2)
  repo = File.basename(org_repo)

  Thread.new do
    repo_dir = File.join(BUNDLE_DIR, repo)
    if Dir.exist?(repo_dir)
      puts "Updating #{org_repo}"
      run!('git', '-C', repo_dir, 'pull')
    else
      puts "Cloning #{org_repo}"
      run!('git', '-C', BUNDLE_DIR, 'clone', "https://github.com/#{org_repo}.git")
    end
    puts "Updating submodules for #{org_repo}"
    run!('git', '-C', repo_dir, 'submodule', 'update', '--init', '--recursive')
    if command
      puts "Running `#{command}` for #{org_repo}"
      run!(command, chdir: repo_dir)
    end
  end
end.map(&:join)
